env:
  global:
    - secure: "Pi8PzUDkfF48uxLfLajgMW5cIqkTqPb7HJCFOQFiCH2QvcbpyFz+2gXoOq1KSsBEqUderMKlvGx7bu6pDjvE6NeDe8QVMKAqRhAQXLpjC4x8OTOgxakYG3/hlm8Gp6caAN0icJF+Jl/3jEOGsRlOvCmnc8h+fY9TNjuyslE4pCkP+jjyJAPaY7/T/pIlaHNJzDLfCz6bdyHmjkhJWisREY1cJQl35q8N/5KjSukC73gFvv2Vw5w/TpxkPDV9zwh90sgFLfkyi95jqREMVqLCu16WcM6MSrQ/I2/ABbCLkQG245s0Kz55GD1uQFjvpzFXAqc9BcOFQowlpOpi4MnYz7776PvyuTP/lrs4xFcXInN9YjVBB5qz86TB5+5L1Ayt1qyRN0TU1/SZe8opw4TCPj/Qnpe82WlKz3GeibzXyCWB/KQ35xPeq6zlSuxv4CHlGz664SWU3puvWH9GQXGSPnXIc/3Y24NLwnpkgUsxU5/nTCzRVN3iVAs5/OXQ/F4L3W+7+SeZyF3cV0S636ZUm7K1ZXfK6hp/Osb12+wvCipejMKwBC+p+LvYx/o5aNnQgLN+TxvF8qinK2Ig2advvMazc8YVYSPSvNHLNR5r37Gheg1CC04yJwwBOnAHlIfo5I5RZDQX3cKSXgNzdffYTqwV0nyPUbo0U62jHOe34y8="

language: node_js
node_js:
- '6'
script: npm install gitbook-cli -g
after_success:
- bash deploy.sh